services:
  postgres:
    image: postgres
    restart: always
    ports:
      - '${DB_PORT:-5432}:5432'
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      start_period: 5s
      retries: 2

  redis:
    image: redis
    restart: always
    command: redis-server --appendonly yes
    # ports:
    #   - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data

  api:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
